from __future__ import annotations

from collections.abc import Iterable, Sequence
from datetime import date
from typing import Protocol
from uuid import UUID

from finnews.domain.entities import (
    Article,
    ArticleCompanyLink,
    ArticleDuplicate,
    ArticleEvent,
    ArticleSentiment,
    Company,
    CompanyAlias,
    DailyCompanySignal,
    DailyDigest,
    IngestionRun,
    NlpEvaluationRun,
    NlpModelRegistryEntry,
    ObservationDisposition,
    PipelineRun,
    RawArticle,
    Source,
    SourceDefinition,
    SourceFetchAttempt,
    SourceFetchState,
)


class NewsRepository(Protocol):
    def upsert_source(self, source: Source) -> Source: ...
    def upsert_source_definition(self, definition: SourceDefinition) -> SourceDefinition: ...
    def list_source_definitions(self) -> list[SourceDefinition]: ...
    def get_source_definition(self, source_id: str) -> SourceDefinition | None: ...
    def upsert_source_fetch_state(self, state: SourceFetchState) -> SourceFetchState: ...
    def get_source_fetch_state(self, source_id: str) -> SourceFetchState | None: ...
    def list_source_fetch_states(self) -> list[SourceFetchState]: ...
    def add_source_fetch_attempt(self, attempt: SourceFetchAttempt) -> SourceFetchAttempt: ...
    def list_source_fetch_attempts(self) -> list[SourceFetchAttempt]: ...
    def upsert_nlp_model(self, model: NlpModelRegistryEntry) -> NlpModelRegistryEntry: ...
    def get_nlp_model(self, model_id: str) -> NlpModelRegistryEntry | None: ...
    def list_nlp_models(
        self, task: str | None = None, status: str | None = None
    ) -> list[NlpModelRegistryEntry]: ...
    def upsert_nlp_evaluation(self, evaluation: NlpEvaluationRun) -> NlpEvaluationRun: ...
    def get_nlp_evaluation(self, evaluation_id: str) -> NlpEvaluationRun | None: ...
    def list_nlp_evaluations(
        self, task: str | None = None, model_id: str | None = None
    ) -> list[NlpEvaluationRun]: ...
    def add_ingestion_run(self, run: IngestionRun) -> IngestionRun: ...
    def add_raw_article(self, raw: RawArticle) -> RawArticle | None: ...
    def add_article(self, article: Article) -> Article | None: ...
    def add_duplicate(self, duplicate: ArticleDuplicate) -> None: ...
    def add_observation_disposition(self, disposition: ObservationDisposition) -> None: ...
    def upsert_company(self, company: Company, aliases: Iterable[str]) -> Company: ...
    def replace_article_links(
        self, article_id: UUID, links: Sequence[ArticleCompanyLink]
    ) -> None: ...
    def replace_article_event(self, event: ArticleEvent) -> None: ...
    def replace_article_sentiment(self, sentiment: ArticleSentiment) -> None: ...
    def upsert_digest(self, digest: DailyDigest) -> DailyDigest: ...
    def upsert_signal(self, signal: DailyCompanySignal) -> DailyCompanySignal: ...
    def add_pipeline_run(self, run: PipelineRun) -> PipelineRun: ...
    def list_articles(self) -> list[Article]: ...
    def list_companies(self) -> list[Company]: ...
    def list_aliases(self) -> list[CompanyAlias]: ...
    def list_links(self) -> list[ArticleCompanyLink]: ...
    def list_events(self) -> list[ArticleEvent]: ...
    def list_sentiments(self) -> list[ArticleSentiment]: ...
    def list_duplicates(self) -> list[ArticleDuplicate]: ...
    def list_observation_dispositions(self) -> list[ObservationDisposition]: ...
    def list_digests(self) -> list[DailyDigest]: ...
    def list_signals(self) -> list[DailyCompanySignal]: ...
    def list_pipeline_runs(self) -> list[PipelineRun]: ...
    def get_article(self, article_id: UUID) -> Article | None: ...
    def get_article_by_hash(self, exact_content_hash: str) -> Article | None: ...
    def get_raw_article_by_id(self, raw_article_id: UUID) -> RawArticle | None: ...
    def get_company_by_ticker(self, ticker: str) -> Company | None: ...
    def get_digest(self, digest_date: date) -> DailyDigest | None: ...


class SourceAdapter(Protocol):
    def read_records(self) -> list[object]: ...
