from __future__ import annotations

from collections.abc import Iterable, Sequence
from datetime import date
from typing import Protocol
from uuid import UUID

from finnews.domain.entities import (
    Article,
    ArticleCompanyLink,
    ArticleDuplicate,
    ArticleEvent,
    ArticleSentiment,
    Company,
    CompanyAlias,
    DailyCompanySignal,
    DailyDigest,
    IngestionRun,
    PipelineRun,
    RawArticle,
    Source,
)


class NewsRepository(Protocol):
    def upsert_source(self, source: Source) -> Source: ...
    def add_ingestion_run(self, run: IngestionRun) -> IngestionRun: ...
    def add_raw_article(self, raw: RawArticle) -> RawArticle | None: ...
    def add_article(self, article: Article) -> Article | None: ...
    def add_duplicate(self, duplicate: ArticleDuplicate) -> None: ...
    def upsert_company(self, company: Company, aliases: Iterable[str]) -> Company: ...
    def replace_article_links(
        self, article_id: UUID, links: Sequence[ArticleCompanyLink]
    ) -> None: ...
    def replace_article_event(self, event: ArticleEvent) -> None: ...
    def replace_article_sentiment(self, sentiment: ArticleSentiment) -> None: ...
    def upsert_digest(self, digest: DailyDigest) -> DailyDigest: ...
    def upsert_signal(self, signal: DailyCompanySignal) -> DailyCompanySignal: ...
    def add_pipeline_run(self, run: PipelineRun) -> PipelineRun: ...
    def list_articles(self) -> list[Article]: ...
    def list_companies(self) -> list[Company]: ...
    def list_aliases(self) -> list[CompanyAlias]: ...
    def list_links(self) -> list[ArticleCompanyLink]: ...
    def list_events(self) -> list[ArticleEvent]: ...
    def list_sentiments(self) -> list[ArticleSentiment]: ...
    def list_duplicates(self) -> list[ArticleDuplicate]: ...
    def list_digests(self) -> list[DailyDigest]: ...
    def list_signals(self) -> list[DailyCompanySignal]: ...
    def list_pipeline_runs(self) -> list[PipelineRun]: ...
    def get_article(self, article_id: UUID) -> Article | None: ...
    def get_company_by_ticker(self, ticker: str) -> Company | None: ...
    def get_digest(self, digest_date: date) -> DailyDigest | None: ...


class SourceAdapter(Protocol):
    def read_records(self) -> list[object]: ...
